### ISSUE TITLE
Dockerize Hasura command

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Backend#28]
# [Backend] Add Hasura CLI Docker Service

Add Hasura CLI service to existing docker-compose.yml for consistent CLI operations.

## Problem
Need to run Hasura CLI commands within Docker environment using existing configuration.

### Updated docker-compose.yml
```yaml
services:
  # ... existing services ...
  
  hasura-cli:
    image: hasura/graphql-engine:v2.42.0.cli-migrations-v3
    volumes:
      - .:/workdir
  working_dir: /workdir
    environment:
      HASURA_GRAPHQL_ENDPOINT: http://graphql-engine:8080
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
    depends_on:
      - graphql-engine
    networks:
      - default
```

### Shell Script (hasura.sh)
```bash
#!/bin/bash
docker-compose run --rm hasura-cli hasura "$@"
```

### Usage
```bash
# Make script executable
chmod +x hasura.sh

# Run commands
./hasura.sh console
./hasura.sh migrate apply
./hasura.sh metadata reload
```

## Success Criteria
- [ ] CLI commands work in Docker environment
- [ ] Migrations and metadata changes persist
- [ ] Console accessible through Docker
- [ ] Environment variables properly set
- [ ] Volume mounting working correctly

## Prerequisites
- [ ] Existing docker-compose.yml
- [ ] Hasura project initialized
- [ ] Docker and docker-compose installed

## Notes
- Uses same Hasura version as graphql-engine
- Shares network with other services
- Mounts local hasura directory
- Inherits environment variables
