### ISSUE TITLE
Implement User Profile Management in Database

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Backend#30]
Add necessary columns and permissions to support user profile management in our existing users table.

## Problem
We need to:
- Extend users table with profile fields
- Set up permissions for profile management
- Support profile image storage in R2
- Handle phone number and location data

## Database Changes

```sql
-- Add profile-related columns to users table
ALTER TABLE users 
ADD COLUMN first_name TEXT,
ADD COLUMN last_name TEXT,
ADD COLUMN summary TEXT,
ADD COLUMN phone_number TEXT,
ADD COLUMN country_code TEXT DEFAULT '+506',
ADD COLUMN location TEXT,
ADD COLUMN profile_image_url TEXT,
ADD COLUMN profile_image_r2_key TEXT;

-- Add validation constraints
ALTER TABLE users
ADD CONSTRAINT valid_phone_format CHECK (phone_number ~ '^\d{8}$'),
ADD CONSTRAINT valid_country_code CHECK (country_code ~ '^\+\d{1,4}$');
```

## Hasura Operations Required

```graphql
# Get user profile
type Query {
  users_by_pk(id: String!): users
}

# Update user profile
type Mutation {
  update_users_by_pk(
    pk_columns: { id: String! }
    _set: users_set_input!
  ): users
}
```

## Permission Rules
```yaml
users:
  select:
    columns:
      - id
      - email
      - first_name
      - last_name
      - summary
      - phone_number
      - country_code
      - location
      - profile_image_url
      - last_seen
    filter:
      id: X-Hasura-User-Id
  
  update:
    columns:
      - first_name
      - last_name
      - summary
      - phone_number
      - country_code
      - location
      - profile_image_url
    filter:
      id: X-Hasura-User-Id
    check:
      id: X-Hasura-User-Id
```

## Migration Files

```sql
-- migrations/XXXXXX_add_profile_fields.up.sql
ALTER TABLE users 
ADD COLUMN first_name TEXT,
ADD COLUMN last_name TEXT,
ADD COLUMN summary TEXT,
ADD COLUMN phone_number TEXT,
ADD COLUMN country_code TEXT DEFAULT '+506',
ADD COLUMN location TEXT,
ADD COLUMN profile_image_url TEXT,
ADD COLUMN profile_image_r2_key TEXT;

ALTER TABLE users
ADD CONSTRAINT valid_phone_format CHECK (phone_number ~ '^\d{8}$'),
ADD CONSTRAINT valid_country_code CHECK (country_code ~ '^\+\d{1,4}$');

-- migrations/XXXXXX_add_profile_fields.down.sql
ALTER TABLE users
DROP CONSTRAINT IF EXISTS valid_phone_format,
DROP CONSTRAINT IF EXISTS valid_country_code;

ALTER TABLE users
DROP COLUMN IF EXISTS first_name,
DROP COLUMN IF EXISTS last_name,
DROP COLUMN IF EXISTS summary,
DROP COLUMN IF EXISTS phone_number,
DROP COLUMN IF EXISTS country_code,
DROP COLUMN IF EXISTS location,
DROP COLUMN IF EXISTS profile_image_url,
DROP COLUMN IF EXISTS profile_image_r2_key;
```

## Success Criteria
- [ ] Database migration successful
- [ ] Permissions properly configured
- [ ] Phone number validation working
- [ ] GraphQL operations tested

## Prerequisites
- [x] Users table exists
- [ ] Hasura permissions system configured
